Lecture 7/hw
DaniilDorovenko/restaurants-app pull request #7
Opened 2024-02-15 06:29 UTC by DaniilDorovenko

Не совсем как рекомендовали по запросам к серверу, но довел свой вариант до рабочего состояния.

2024-02-15 15:49 UTC, SArchieEdu requested changes

2024-02-15 15:49 UTC, SArchieEdu commented on src/redux/entities/user/index.js
не нашел тут добавления юзеров

2024-02-15 15:49 UTC, SArchieEdu commented on src/components/dish/component.jsx
> +    }, [dispatch, dishId]);
не стоит делать запрос за каждым блюдом отдельно. Если будет список из ста блюд, то это сто запросов. лучше переделать как на лекции разбирали

2024-02-18 11:18 UTC, DaniilDorovenko commented on src/components/dish/component.jsx
> +    }, [dispatch, dishId]);
Ипсравил

2024-02-18 11:19 UTC, DaniilDorovenko commented on src/redux/entities/user/index.js
Не понял, у нас нет в этом задании добавления юзеров...

2024-02-19 14:57 UTC, SArchieEdu requested changes

2024-02-19 14:57 UTC, SArchieEdu commented on src/redux/entities/user/index.js
Добавление юзеров в стейт. необходимо было грузить рестораны, блюда, отзывы и юзеров с сервера

2024-02-19 16:59 UTC, DaniilDorovenko commented
Добавил юзеров

2024-02-22 15:37 UTC, SArchieEdu approved these changes

2024-02-22 15:37 UTC, SArchieEdu commented on src/components/menu/component.jsx
> +    const { data: menu } = useGetMenuQuery(restaurantId);
это уже из 8 дз

2024-02-23 05:45 UTC, merged